export const citys = [,
  {label: 'Itagüí', value: 'Itagüí'},
  {label: 'Envigado', value: 'Envigado'},
  {label: 'Sabaneta', value: 'Sabaneta'},
  {label: 'La Estrella', value: 'La Estrella'},
  {label: 'San Antonio de Prado', value: 'San Antonio de Prado'},
  {label: 'Caldas', value: 'Caldas, Antioquia'},
  {label: 'Bello', value: 'Bello'},
  {label: 'Copacabana', value: 'Copacabana'},
  {label: 'Girardota', value: 'Girardota'},
  {label: 'Barbosa', value: 'Barbosa'},
  {label: 'Guarne', value: 'Guarne'},
  {label: 'Rionegro', value: 'Rionegro'},
  {label: 'Marinilla', value: 'Marinilla'},
  {label: 'El Retiro', value: 'El retiro'},
  {label: 'La ceja', value: 'La ceja'},
  {label: 'Sopetrán', value: 'Sopetrán'},
  {label: 'Santa Fe de Antioquia', value: 'Santa Fe de Antioquia'},
  {label: 'La ceja', value: 'La ceja'},
    {label: 'Medellín', value: 'Medellin'},
    {label: 'Bogotá', value: 'Bogota'},
    {label: 'Cali', value: 'Cali'},
    {label: 'B/qlla', value: 'Barranquilla'},
    {label: 'Cartagena', value: 'Cartagena'},
    {label: 'Londres', value: 'London'},
  ]